import React, { useState, useEffect } from 'react';
import { collection, getDocs, deleteDoc, doc, addDoc, orderBy, query, updateDoc } from 'firebase/firestore';
import { db, auth } from '../lib/firebase';
import { useAuth } from '../contexts/AuthContext';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/Card';
import { Trash2, Plus, Shield, User, X, Download, FileJson } from 'lucide-react';
import { handleFirebaseError } from '../lib/firebase-errors';
import toast from 'react-hot-toast';
import { UserProfile } from '../types';

export const Settings = () => {
  const { userProfile, isAdmin } = useAuth();
  const [parties, setParties] = useState<{ id: string; name: string }[]>([]);
  const [transports, setTransports] = useState<{ id: string; name: string }[]>([]);
  const [users, setUsers] = useState<UserProfile[]>([]);
  const [newParty, setNewParty] = useState('');
  const [newTransport, setNewTransport] = useState('');
  const [loading, setLoading] = useState(true);
  const [showRules, setShowRules] = useState(true);

  useEffect(() => {
    fetchParties();
    fetchTransports();
    if (isAdmin) {
      fetchUsers();
    }
  }, [isAdmin]);

  const handleDownloadTDL = () => {
    const appUrl = window.location.origin;
    const tdlContent = `;; Parcel Tracker Integration for Tally Prime
;; Generated by Parcel Tracker App
;; VERSION: 3.2 (Stable Fix)

[System: Formula]
    ParcelTrackerURL: "${appUrl}/api/tally/check-lr"

;; ==========================================
;; 1. VERIFICATION
;; ==========================================
[#Menu: Gateway of Tally]
    Add: Item: "Check Parcel Tracker Connection" : Call: TestConnection

[Function: TestConnection]
    00: Msg Box: "Status": "✅ Parcel Tracker TDL is Successfully Loaded! URL: " + @@ParcelTrackerURL

;; ==========================================
;; 2. DATA STORAGE
;; ==========================================
[System: UDF]
    PT_LRNo: String: 1001
    PT_Status: String: 1002
    PT_Transport: String: 1003
    PT_Details: String: 1004

;; ==========================================
;; 3. UI INTEGRATION
;; ==========================================

;; Target "Purchase Color" (The Standard Purchase Invoice Screen)
;; Note: We removed "Purchase" and "Purchase Voucher" as they caused errors in your Tally version.
[#Form: Purchase Color]
    Add: Part: After: VCH Narration: PT_Main_Part
    Add: Button: At End: PT_Check_Btn

;; Button Definition
[Button: PT_Check_Btn]
    Title: "Check Parcel (Ctrl+Alt+P)"
    Key: Ctrl + Alt + P
    Action: Call: CheckParcelStatus
    Color: Deep Blue

;; Main Container Part
[Part: PT_Main_Part]
    Line: PT_Title_Line, PT_Input_Line, PT_Result_Line
    Border: Thin Box
    Space Top: 1
    Background: White

[Line: PT_Title_Line]
    Field: Simple Field
    Local: Field: Simple Field: Set as: "PARCEL TRACKER INTEGRATION"
    Local: Field: Simple Field: Style: Small Bold
    Local: Field: Simple Field: Color: Deep Blue
    Local: Field: Simple Field: Full Width: Yes
    Local: Field: Simple Field: Align: Center
    Local: Field: Simple Field: Skip: Yes

[Line: PT_Input_Line]
    Field: Medium Prompt, PT_LR_Field
    Local: Field: Medium Prompt: Set as: "Enter LR Number:"
    Local: Field: Medium Prompt: Width: 20
    Local: Field: Medium Prompt: Color: Blue

[Field: PT_LR_Field]
    Use: Name Field
    Storage: PT_LRNo
    Width: 25
    Border: Thin Box
    Background: White
    On: Accept: Call: CheckParcelStatus

[Line: PT_Result_Line]
    Field: Medium Prompt, PT_Status_Field, Medium Prompt, PT_Info_Field
    Local: Field: Medium Prompt: Set as: "Status:"
    Local: Field: Medium Prompt: Width: 10
    Local: Field: Medium Prompt: Color: Blue

[Field: PT_Status_Field]
    Use: Name Field
    Storage: PT_Status
    Set as: if $$IsEmpty:$PT_Status then "Pending" else $PT_Status
    Color: if $PT_Status = "RECEIVED" then Green else Red
    Width: 15
    Skip: Yes
    Border: Thin Box
    Background: White

[Field: PT_Info_Field]
    Use: Name Field
    Storage: PT_Details
    Set as: $PT_Details
    Width: 40
    Skip: Yes
    Style: Small Italic
    Border: Thin Box
    Background: White

;; ==========================================
;; 4. LOGIC
;; ==========================================
[Function: CheckParcelStatus]
    Variable: LRNum: String
    Variable: ServerResponse: String
    Variable: StatusPart: String
    Variable: TransPart: String
    Variable: WeightPart: String
    Variable: AmountPart: String
    
    ;; Get LR Number from field
    00: Set: LRNum: $PT_LRNo
    10: If: $$IsEmpty: ##LRNum
    20:     Query Box: "Enter LR Number": Yes: No
    30:     If: $$LastResult
    40:         Set: LRNum: $$EditData
    50:         Field Set: PT_LR_Field: ##LRNum
    60:     Else
    70:         Return
    80:     End If
    90: End If

    100: Msg Box: "Checking...": "Connecting to Parcel Tracker..."
    110: Set: ServerResponse: $$FetchUrl:@@ParcelTrackerURL + "?lr=" + ##LRNum + "&format=text"
    
    ;; Parse Response: STATUS|TRANSPORT|WEIGHT|AMOUNT
    120: Set: StatusPart: $$StringPart:##ServerResponse:0:"|"
    130: Set: TransPart: $$StringPart:##ServerResponse:1:"|"
    140: Set: WeightPart: $$StringPart:##ServerResponse:2:"|"
    145: Set: AmountPart: $$StringPart:##ServerResponse:3:"|"

    150: If: ##StatusPart = "RECEIVED"
    160:    Field Set: PT_Status_Field: "RECEIVED"
    170:    Field Set: PT_Info_Field: ##TransPart + " (" + ##WeightPart + " / Rs." + ##AmountPart + ")"
    180:    Set: PT_Status: "RECEIVED"
    190:    Set: PT_Details: ##TransPart + " (" + ##WeightPart + " / Rs." + ##AmountPart + ")"
    200:    Msg Box: "Success": "✅ Parcel Found! Status: RECEIVED"
    210: Else
    220:    Field Set: PT_Status_Field: "NOT RECEIVED"
    230:    Field Set: PT_Info_Field: "Unknown"
    240:    Set: PT_Status: "NOT RECEIVED"
    250:    Set: PT_Details: "Unknown"
    260:    Msg Box: "Not Found": "❌ Parcel NOT Found or Not Received."
    270: End If
`;
    
    const blob = new Blob([tdlContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'ParcelTracker.tdl';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('TDL file downloaded');
  };

  const fetchTransports = async () => {
    try {
      const q = query(collection(db, 'transports'), orderBy('name'));
      const snapshot = await getDocs(q);
      setTransports(snapshot.docs.map(doc => ({ id: doc.id, name: doc.data().name })));
    } catch (error) {
      console.error("Error fetching transports:", error);
    }
  };

  const fetchParties = async () => {
    try {
      // 1. Fetch all parcels to count party occurrences
      const parcelsSnapshot = await getDocs(collection(db, 'parcels'));
      const counts: Record<string, number> = {};
      parcelsSnapshot.forEach(doc => {
        const pName = doc.data().partyName;
        if (pName) counts[pName] = (counts[pName] || 0) + 1;
      });

      // 2. Fetch all parties
      const q = query(collection(db, 'parties'), orderBy('name'));
      const snapshot = await getDocs(q);
      const partyList = snapshot.docs.map(doc => ({ id: doc.id, name: doc.data().name }));

      // 3. Sort by frequency (descending), then by name (ascending)
      const sortedParties = partyList.sort((a, b) => {
        const countA = counts[a.name] || 0;
        const countB = counts[b.name] || 0;
        if (countB !== countA) return countB - countA;
        return a.name.localeCompare(b.name);
      });

      setParties(sortedParties);
    } catch (error) {
      handleFirebaseError(error);
    } finally {
      setLoading(false);
    }
  };

  const fetchUsers = async () => {
    try {
      const q = query(collection(db, 'users'));
      const snapshot = await getDocs(q);
      // Ensure uid is populated from doc.id if missing in data
      setUsers(snapshot.docs.map(doc => {
        const data = doc.data();
        return { 
          ...data, 
          uid: doc.id, // Always use doc.id as the uid source of truth
          email: data.email || '',
          role: data.role || 'staff'
        } as UserProfile;
      }));
    } catch (error) {
      console.error("Error fetching users:", error);
    }
  };

  const updateUserRole = async (uid: string, currentRole: string) => {
    const newRole = currentRole === 'admin' ? 'staff' : 'admin';
    try {
      await updateDoc(doc(db, 'users', uid), { role: newRole });
      toast.success('User role updated');
      fetchUsers();
    } catch (error) {
      handleFirebaseError(error);
    }
  };

  const handleAddParty = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newParty.trim()) return;

    try {
      await addDoc(collection(db, 'parties'), { name: newParty.trim() });
      setNewParty('');
      fetchParties();
      toast.success('Party added');
    } catch (error) {
      handleFirebaseError(error);
    }
  };

  const handleDeleteParty = async (id: string) => {
    if (!isAdmin) {
      toast.error('Only admins can delete parties');
      return;
    }
    if (!confirm('Delete this party?')) return;
    try {
      await deleteDoc(doc(db, 'parties', id));
      setParties(parties.filter(p => p.id !== id));
      toast.success('Party deleted');
    } catch (error) {
      handleFirebaseError(error);
    }
  };

  const handleAddTransport = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTransport.trim()) return;

    try {
      await addDoc(collection(db, 'transports'), { name: newTransport.trim() });
      setNewTransport('');
      fetchTransports();
      toast.success('Transport added');
    } catch (error) {
      handleFirebaseError(error);
    }
  };

  const handleDeleteTransport = async (id: string) => {
    if (!isAdmin) {
      toast.error('Only admins can delete transports');
      return;
    }
    if (!confirm('Delete this transport?')) return;
    try {
      await deleteDoc(doc(db, 'transports', id));
      setTransports(transports.filter(t => t.id !== id));
      toast.success('Transport deleted');
    } catch (error) {
      handleFirebaseError(error);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <h2 className="text-2xl font-bold tracking-tight">Settings</h2>

      {showRules && (
        <Card className="bg-amber-50 border-amber-200 relative">
          <button 
            onClick={() => setShowRules(false)}
            className="absolute top-4 right-4 text-amber-700 hover:text-amber-900"
          >
            <X size={16} />
          </button>
          <CardHeader>
            <CardTitle className="text-amber-800 flex items-center gap-2">
              <Shield size={20} />
              Firebase Security Rules
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-amber-700 mb-4">
              If you experienced "Missing permissions" errors, ensure your Firestore Rules are updated in the Firebase Console:
            </p>
            <div className="bg-slate-900 text-slate-50 p-3 rounded-md text-xs font-mono overflow-x-auto">
              <pre>{`match /{document=**} { allow read, write: if request.auth != null; }`}</pre>
            </div>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle>Your Profile</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-between p-4 bg-slate-50 rounded-lg border border-slate-100">
            <div className="flex items-center gap-4">
              <div className="p-3 bg-indigo-100 text-indigo-600 rounded-full">
                <User size={24} />
              </div>
              <div>
                <p className="font-medium text-slate-900">{userProfile?.email}</p>
                <div className="flex items-center gap-2 mt-1">
                  <span className={`text-xs font-bold px-2 py-0.5 rounded-full uppercase ${userProfile?.role === 'admin' ? 'bg-indigo-100 text-indigo-700' : 'bg-slate-200 text-slate-700'}`}>
                    {userProfile?.role}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileJson size={20} className="text-indigo-600" />
            Tally Prime Integration
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="bg-indigo-50 border border-indigo-100 rounded-lg p-4 mb-4">
            <h4 className="font-semibold text-indigo-900 mb-2">How to Integrate with Tally Prime</h4>
            <ol className="list-decimal list-inside text-sm text-indigo-800 space-y-2">
              <li>Download the TDL file using the button below.</li>
              <li>Open Tally Prime and go to <strong>Help &gt; TDL & Add-On &gt; Manage Local TDLs</strong>.</li>
              <li>Select the downloaded file <code>ParcelTracker.tdl</code>.</li>
              <li>Set "Load TDL" to <strong>Yes</strong>.</li>
              <li>Go to <strong>Purchase Voucher</strong>. You will see a new field "Check LR Number".</li>
              <li>Enter an LR Number to instantly check its status in this tracker.</li>
            </ol>
          </div>
          <Button onClick={handleDownloadTDL} className="w-full sm:w-auto">
            <Download size={18} className="mr-2" /> Download TDL File
          </Button>
        </CardContent>
      </Card>

      {isAdmin && (
        <Card>
          <CardHeader>
            <CardTitle>User Management</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="overflow-hidden rounded-lg border border-slate-200">
              <table className="w-full text-sm text-left">
                <thead className="bg-slate-50 text-slate-500 uppercase text-xs">
                  <tr>
                    <th className="px-4 py-3">Email</th>
                    <th className="px-4 py-3">Role</th>
                    <th className="px-4 py-3 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {users.map((user) => (
                    <tr key={user.uid} className="bg-white">
                      <td className="px-4 py-3 font-medium">{user.email}</td>
                      <td className="px-4 py-3">
                        <span className={`px-2 py-1 rounded-full text-xs font-bold uppercase ${user.role === 'admin' ? 'bg-indigo-100 text-indigo-700' : 'bg-slate-100 text-slate-600'}`}>
                          {user.role}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-right">
                        {user.uid !== auth.currentUser?.uid && (
                          <Button 
                            variant="ghost" 
                            size="sm"
                            onClick={() => updateUserRole(user.uid, user.role)}
                          >
                            Make {user.role === 'admin' ? 'Staff' : 'Admin'}
                          </Button>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle>Manage Parties</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleAddParty} className="flex gap-4 mb-6">
            <Input
              placeholder="Enter new party name"
              value={newParty}
              onChange={(e) => setNewParty(e.target.value)}
              className="flex-1"
            />
            <Button type="submit">
              <Plus size={18} className="mr-2" /> Add Party
            </Button>
          </form>

          <div className="bg-slate-50 rounded-lg border border-slate-200 overflow-hidden max-h-60 overflow-y-auto">
            {loading ? (
              <div className="p-4 text-center text-slate-500">Loading...</div>
            ) : parties.length === 0 ? (
              <div className="p-4 text-center text-slate-500">No parties found.</div>
            ) : (
              <ul className="divide-y divide-slate-200">
                {parties.map((party) => (
                  <li key={party.id} className="p-3 flex items-center justify-between hover:bg-white transition-colors">
                    <span className="font-medium text-slate-700">{party.name}</span>
                    {isAdmin && (
                      <button
                        onClick={() => handleDeleteParty(party.id)}
                        className="text-slate-400 hover:text-red-600 transition-colors"
                      >
                        <Trash2 size={16} />
                      </button>
                    )}
                  </li>
                ))}
              </ul>
            )}
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Manage Transports</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleAddTransport} className="flex gap-4 mb-6">
            <Input
              placeholder="Enter new transport name"
              value={newTransport}
              onChange={(e) => setNewTransport(e.target.value)}
              className="flex-1"
            />
            <Button type="submit">
              <Plus size={18} className="mr-2" /> Add Transport
            </Button>
          </form>

          <div className="bg-slate-50 rounded-lg border border-slate-200 overflow-hidden max-h-60 overflow-y-auto">
            {loading ? (
              <div className="p-4 text-center text-slate-500">Loading...</div>
            ) : transports.length === 0 ? (
              <div className="p-4 text-center text-slate-500">No transports found.</div>
            ) : (
              <ul className="divide-y divide-slate-200">
                {transports.map((transport) => (
                  <li key={transport.id} className="p-3 flex items-center justify-between hover:bg-white transition-colors">
                    <span className="font-medium text-slate-700">{transport.name}</span>
                    {isAdmin && (
                      <button
                        onClick={() => handleDeleteTransport(transport.id)}
                        className="text-slate-400 hover:text-red-600 transition-colors"
                      >
                        <Trash2 size={16} />
                      </button>
                    )}
                  </li>
                ))}
              </ul>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
};
